// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/app/components/widgets/AppLogo.vue')['default']
    Cookies: typeof import('./src/app/components/Cookies.vue')['default']
    JupyterNotebook: typeof import('./src/app/components/JupyterNotebook.vue')['default']
    RendererRootViewPortComponent: typeof import('./src/app/components/renderer/RendererRootViewPortComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewPortComponent: typeof import('./src/app/components/renderer/ViewPortComponent.vue')['default']
  }
}
