# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20.14"
      # install node deps
      - run: npm install
      # build wasm deps
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      # build node
      - run: npm run build:wasm
      - run: npx nuxt build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./.output/public
  # Deployment job
  deploy:
    # # Add a dependency to the build job
    # needs: build
    # # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # permissions:
    #   pages: write      # to deploy to Pages
    #   id-token: write   # to verify the deployment originates from an appropriate source
    # # Deploy to the github_pages environment
    # environment:
    #   name: github_pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


# name: cd

# on: [push, pull_request]

# jobs:
#   cd:
#     runs-on: ${{ matrix.os }}

#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#         node: [v18.16.1]

#     steps:
#       - name: Checkout
#         uses: actions/checkout@master

#       - name: Setup node env
#         uses: actions/setup-node@v2.1.2
#         with:
#           node-version: ${{ matrix.node }}

#       - uses: Swatinem/rust-cache@v2

#       - uses: jetli/wasm-pack-action@v0.4.0
#         with:
#           version: 'latest'
  
#       - run: npm run build:wasm

#       - name: Install node dependencies
#         run: npm install

#       - name: Generate
#         run: npm run generate

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./.output/public
