name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      # - name: Install Rust toolchain
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     target: wasm32-unknown-unknown

      # - uses: Swatinem/rust-cache@v2


      # - name: Install wasm-pack
      #   # Use workspace target directory for cargo install's build,
      #   # so that the build of wasm-pack will be cached by rust-cache action.
      #   run: CARGO_TARGET_DIR=`pwd`/target cargo install wasm-pack
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.9.1
      - run: |
          npm run build:wasm

      - name: Install node dependencies
        run: npm install

      - name: Build WASM dependencies
        run: npm run build:wasm

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
